"""Session storage: S3 + DynamoDB synchronization."""
import time
from pathlib import Path
from typing import Optional
from botocore.exceptions import ClientError
import boto3


class SessionStore:
    """Manage session files in S3 and session_id mapping in DynamoDB.

    Note: session_id is generated by Claude Code SDK, not by this class.
    We only store the mapping: chat_id:thread_id → session_id (from SDK)
    """

    def __init__(self, bucket: str, table: str, project_path: str):
        """Initialize SessionStore.

        Args:
            bucket: S3 bucket name for session storage
            table: DynamoDB table name for session mapping
            project_path: Project path for local file storage (e.g., "-tmp-workspace")
        """
        self.s3 = boto3.client('s3')
        self.dynamodb = boto3.resource('dynamodb').Table(table)
        self.bucket = bucket
        self.project_path = project_path
        self.home = Path.home()
        self.claude_dir = self.home / '.claude'

    def get_session_id(
        self,
        chat_id: str,
        thread_id: Optional[str] = None
    ) -> Optional[str]:
        """Get existing session_id from DynamoDB.

        Args:
            chat_id: Telegram chat ID
            thread_id: Optional Telegram thread ID (for topics)

        Returns:
            session_id if exists, None otherwise
        """
        session_key = f"{chat_id}:{thread_id or 'default'}"

        try:
            response = self.dynamodb.get_item(Key={'session_key': session_key})
            if 'Item' in response:
                return response['Item']['session_id']
        except Exception as e:
            print(f"Warning: Failed to query DynamoDB: {e}")

        return None

    def save_session_id(
        self,
        chat_id: str,
        thread_id: Optional[str],
        session_id: str
    ) -> None:
        """Save session_id mapping to DynamoDB.

        Called after SDK returns a new session_id.

        Args:
            chat_id: Telegram chat ID
            thread_id: Optional Telegram thread ID
            session_id: Session ID returned by Claude Code SDK
        """
        session_key = f"{chat_id}:{thread_id or 'default'}"

        try:
            self.dynamodb.put_item(
                Item={
                    'session_key': session_key,
                    'session_id': session_id,
                    'chat_id': chat_id,
                    'thread_id': thread_id or 'default',
                    'created_at': int(time.time()),
                    'updated_at': int(time.time()),
                    'ttl': int(time.time()) + (25 * 24 * 3600),  # 25 days
                }
            )
            print(f"Saved session mapping: {session_key} → {session_id}")
        except Exception as e:
            print(f"Warning: Failed to save session in DynamoDB: {e}")

    def update_session_timestamp(
        self,
        chat_id: str,
        thread_id: Optional[str] = None
    ) -> None:
        """Update session timestamp in DynamoDB."""
        session_key = f"{chat_id}:{thread_id or 'default'}"

        try:
            self.dynamodb.update_item(
                Key={'session_key': session_key},
                UpdateExpression='SET updated_at = :t, #ttl = :ttl',
                ExpressionAttributeNames={'#ttl': 'ttl'},
                ExpressionAttributeValues={
                    ':t': int(time.time()),
                    ':ttl': int(time.time()) + (25 * 24 * 3600),
                }
            )
        except Exception as e:
            print(f"Warning: Failed to update session timestamp: {e}")

    def download_session_files(self, session_id: str) -> None:
        """Download session files from S3 to ~/.claude/.

        Files downloaded:
        - s3://bucket/sessions/{session_id}/conversation.jsonl
            → ~/.claude/projects/{project_path}/{session_id}.jsonl
        - s3://bucket/sessions/{session_id}/debug.txt
            → ~/.claude/debug/{session_id}.txt
        - s3://bucket/sessions/{session_id}/todos.json
            → ~/.claude/todos/{session_id}-agent-{session_id}.json

        Args:
            session_id: Session ID to download files for
        """
        files = [
            ('conversation.jsonl', f'projects/{self.project_path}/{session_id}.jsonl'),
            ('debug.txt', f'debug/{session_id}.txt'),
            ('todos.json', f'todos/{session_id}-agent-{session_id}.json'),
        ]

        for s3_name, local_path in files:
            s3_key = f'sessions/{session_id}/{s3_name}'
            local_file = self.claude_dir / local_path
            local_file.parent.mkdir(parents=True, exist_ok=True)

            try:
                self.s3.download_file(self.bucket, s3_key, str(local_file))
                print(f"Downloaded {s3_key} → {local_file}")
            except ClientError as e:
                error_code = e.response.get('Error', {}).get('Code', '')
                if error_code in ('NoSuchKey', '404'):
                    # File doesn't exist yet (new session)
                    print(f"S3 file {s3_key} not found, will be created after agent runs")
                else:
                    print(f"Warning: Failed to download {s3_key}: {e}")

    def upload_session_files(self, session_id: str) -> None:
        """Upload session files from ~/.claude/ to S3.

        Files uploaded:
        - ~/.claude/projects/{project_path}/{session_id}.jsonl
            → s3://bucket/sessions/{session_id}/conversation.jsonl
        - ~/.claude/debug/{session_id}.txt
            → s3://bucket/sessions/{session_id}/debug.txt
        - ~/.claude/todos/{session_id}-agent-{session_id}.json
            → s3://bucket/sessions/{session_id}/todos.json

        Args:
            session_id: Session ID to upload files for
        """
        files = [
            (f'projects/{self.project_path}/{session_id}.jsonl', 'conversation.jsonl'),
            (f'debug/{session_id}.txt', 'debug.txt'),
            (f'todos/{session_id}-agent-{session_id}.json', 'todos.json'),
        ]

        for local_path, s3_name in files:
            local_file = self.claude_dir / local_path
            if local_file.exists() and local_file.stat().st_size > 0:
                s3_key = f'sessions/{session_id}/{s3_name}'
                try:
                    self.s3.upload_file(str(local_file), self.bucket, s3_key)
                    print(f"Uploaded {local_file} → {s3_key}")
                except Exception as e:
                    print(f"Warning: Failed to upload {s3_key}: {e}")
            else:
                print(f"Skipping empty/missing file: {local_file}")
